polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/vote_answer', views.vote_answer, name='vote_answer'),
    path('<int:question_id>/unvote_answer', views.unvote_answer, name='unvote_answer'),
    path('<int:question_id>/delete_answer', views.delete_answer, name='delete_answer'),
    path('<int:question_id>/add_answer', views.add_answer, name='add_answer'),
]

trydjango/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls)
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    timestamp = models.DateTimeField('Date Published')

    def __str__(self):
        return self.question_text

class Answer(models.Model):
    question = models.OneToOneField(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)
    votes = models.IntegerField(default = 0)

    def __str__(self):
        return self.answer_text

polls/views.py
from django.shortcuts import render, redirect

from .models import Question, Answer

def index(request):
    latest_question_list = Question.objects.all()
    context = {
        'latest_question_list' : latest_question_list,
    }
    
    return render(request, 'polls/index.html', context)

def add_answer(request, question_id):
    q = Question.objects.get(pk=question_id)    
    ans = Answer(question = q, answer_text = request.POST['input-answer'], votes = 0)
    print('request', request, q, ans)
    ans.save()

    return redirect('/polls/')

def delete_answer(request, question_id):
    ans = Question.objects.get(pk=question_id).answer
    ans.delete()    
        
    return redirect('/polls/')

def vote_answer(request, question_id):    
    ans = Question.objects.get(pk=question_id).answer
    ans.votes += 1

    ans.save()

    return redirect('/polls/')

def unvote_answer(request, question_id):    
    ans = Question.objects.get(pk=question_id).answer
    ans.votes -= 1

    ans.save()

    return redirect('/polls/')

trydjango/views.py
from django.shortcuts import redirect

def index(request):
    return redirect('/polls/')

polls/templates/polls/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Question and Answer Polls</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.0.0-beta.4/dist/css/bootstrap-material-design.min.css" integrity="sha384-R80DC0KVBO4GSTw+wZ5x2zn2pu4POSErBkf8/fSFhPXHxvHJydT0CSgAP2Yo2r4I" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    {% if latest_question_list %}
            {% for question in latest_question_list %}
            <div class="modal fade" id="answer-{{ question.id }}" tabindex="-1" role="dialog" aria-labelledby="answer-{{ question.id }}-label" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="answer-{{ question.id }}-label">Give Your Answer</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{% url 'polls:add_answer' question.id %}" method="POST">{% csrf_token %}
                <div class="modal-body">
                      <div class="form-group">
                        <label for="input-answer">Answer</label>
                        <input type="text" class="form-control" id="input-answer" name='input-answer' aria-describedby="answerHelp" placeholder="Type Answer">
                        <small id="answerHelp" class="form-text text-muted">(max 200 characters)</small>
                      </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
                </div>
                </form>
            </div>
            </div>

            <div class="row justify-content-center">
                    <div class="col-lg-8 col-md-10 col-sm-12">
                        <div class="card">
                            <div class="card-header">
                                Question # {{ forloop.counter }}
                                <span style="float : right;">
                                Posted {{ question.timestamp }}
                                </span>
                            </div>

                            <div class="card-body">
                                <table class="table table-borderless">
                                    <tbody>
                                        <tr>
                                            <td>Question: </td>
                                            <td>{{ question.question_text }}</td>
                                        </tr>
                                        <tr>
                                            <td>Answer: </td>
                                    {% if not question.answer %}
                                            <td width="99.9%%">
                                                <b> None </b>
                                                <a type="button" class="btn btn-success" data-toggle="modal" data-target="#answer-{{ question.id }}" style="float: right;">Add Answer</a>
                                            </td>
                                        </tr>
                                    {% else %}
                                            <td>
                                                {{ question.answer }}
                                                <span class="fas fa-star" style="float : right;"> {{ question.answer.votes }} </span>
                                            </td>
                                            </tr>
                                            <tr>
                                            <td>
                                                <a href="{% url 'polls:vote_answer' question.id %}" type="button" class="btn btn-default">
                                                    <span class="fas fa-arrow-up"> </span> Vote
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'polls:unvote_answer' question.id %}" type="button" class="btn btn-default">
                                                    <span class="fas fa-arrow-down"> </span> Unvote
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'polls:delete_answer' question.id %}" type="button" class="btn btn-danger">
                                                    <span class="fas fa-trash-alt"> </span> Delete
                                                </a>
                                            </td>
                                        </tr>
                                    {% endif %}
                                    </tbody>
                                </table>
                            </div>
                    </div>
                </div>
            </div>
            {% endfor %}
    {% else %}
        <div class="row justify-content-center">
                <div class="col-lg-8 col-md-10 col-sm-12">
                    <div class="card">
                        <div class="card-header">No Question Available</div>
                </div>
            </div>
        </div>
    {% endif %}
    
</div>
</body>
</html>